修改actions

diff --git a/.github/workflows/Sync_Obsidian.yml b/.github/workflows/Sync_Obsidian.yml
--- a/.github/workflows/Sync_Obsidian.yml
+++ b/.github/workflows/Sync_Obsidian.yml
@@ -11,6 +11,9 @@ on:
 jobs:
   sync:
     runs-on: ubuntu-latest
+    concurrency:
+      group: 'sync-obsidian'  # 确保只有一个工作流在运行
+      cancel-in-progress: true  # 如果有新的请求，则取消当前请求
 
     steps:
     - name: Checkout Obsidian repository
@@ -27,52 +30,29 @@ jobs:
         path: wangyunzi.github.io
         token: ${{ secrets.BLOG_REPO_TOKEN }}
 
-    - name: Sync _pages folder
+    - name: Sync folders
       run: |
-        rsync -av --delete myob/日记本/blog/pages/ wangyunzi.github.io/_pages/
-        cd wangyunzi.github.io
-        find _pages -name "*.md" -exec sed -i -E '
-          s/date: ([0-9]{4}-[0-9]{2}-[0-9]{2})T([0-9]{2}:[0-9]{2}:[0-9]{2})([+-][0-9]{2}:[0-9]{2}|)/date: \1 \2 +0800/
-          s/date: ([0-9]{4}-[0-9]{2}-[0-9]{2})T([0-9]{2}:[0-9]{2}:[0-9]{2})[+-][0-9]{2}:[0-9]{2}/date: \1 \2 +0800/
-          s/date: ([0-9]{4}-[0-9]{2}-[0-9]{2}) ([0-9]{2}:[0-9]{2}:[0-9]{2})/date: \1 \2 +0800/
-        ' {} \;
-        git config user.name "GitHub Actions"
-        git config user.email "actions@github.com"
-        git add _pages
-        git commit -m "Sync _pages from Obsidian repository" || echo "No changes in _pages"
-        cd -
+        sync_folder() {
+          local folder=$1
+          rsync -av --delete myob/日记本/blog/$folder/ wangyunzi.github.io/$folder/
+          cd wangyunzi.github.io || exit
+          find $folder -name "*.md" -exec sed -i -E '
+            s/date: ([0-9]{4}-[0-9]{2}-[0-9]{2})T([0-9]{2}:[0-9]{2}:[0-9]{2})([+-][0-9]{2}:[0-9]{2}|)/date: \1 \2 +0800/
+            s/date: ([0-9]{4}-[0-9]{2}-[0-9]{2})T([0-9]{2}:[0-9]{2}:[0-9]{2})[+-][0-9]{2}:[0-9]{2}/date: \1 \2 +0800/
+            s/date: ([0-9]{4}-[0-9]{2}-[0-9]{2}) ([0-9]{2}:[0-9]{2}:[0-9]{2})/date: \1 \2 +0800/
+          ' {} \;
+          git config user.name "GitHub Actions"
+          git config user.email "actions@github.com"
+          git add $folder
+          git commit -m "Sync $folder from Obsidian repository" || echo "No changes in $folder"
+          cd - || exit
+        }
 
-    - name: Sync _album folder
-      run: |
-        rsync -av --delete myob/日记本/blog/album/ wangyunzi.github.io/_album/
-        cd wangyunzi.github.io
-        find _album -name "*.md" -exec sed -i -E '
-          s/date: ([0-9]{4}-[0-9]{2}-[0-9]{2})T([0-9]{2}:[0-9]{2}:[0-9]{2})([+-][0-9]{2}:[0-9]{2}|)/date: \1 \2 +0800/
-          s/date: ([0-9]{4}-[0-9]{2}-[0-9]{2})T([0-9]{2}:[0-9]{2}:[0-9]{2})[+-][0-9]{2}:[0-9]{2}/date: \1 \2 +0800/
-          s/date: ([0-9]{4}-[0-9]{2}-[0-9]{2}) ([0-9]{2}:[0-9]{2}:[0-9]{2})/date: \1 \2 +0800/
-        ' {} \;
-        git config user.name "GitHub Actions"
-        git config user.email "actions@github.com"
-        git add _album
-        git commit -m "Sync _album from Obsidian repository" || echo "No changes in _album"
-        cd -
-
-    - name: Sync _posts folder
-      run: |
-        rsync -av --delete myob/日记本/blog/posts/ wangyunzi.github.io/_posts/
-        cd wangyunzi.github.io
-        find _posts -name "*.md" -exec sed -i -E '
-          s/date: ([0-9]{4}-[0-9]{2}-[0-9]{2})T([0-9]{2}:[0-9]{2}:[0-9]{2})([+-][0-9]{2}:[0-9]{2}|)/date: \1 \2 +0800/
-          s/date: ([0-9]{4}-[0-9]{2}-[0-9]{2})T([0-9]{2}:[0-9]{2}:[0-9]{2})[+-][0-9]{2}:[0-9]{2}/date: \1 \2 +0800/
-          s/date: ([0-9]{4}-[0-9]{2}-[0-9]{2}) ([0-9]{2}:[0-9]{2}:[0-9]{2})/date: \1 \2 +0800/
-        ' {} \;
-        git config user.name "GitHub Actions"
-        git config user.email "actions@github.com"
-        git add _posts
-        git commit -m "Sync _posts from Obsidian repository" || echo "No changes in _posts"
-        cd -
+        for folder in _pages _album _posts; do
+          sync_folder $folder
+        done
 
     - name: Push changes
       run: |
-        cd wangyunzi.github.io
-        git push
+        cd wangyunzi.github.io || exit
+        git push || echo "Failed to push changes. Please check the repository."
